Feat:[공통] Pagination 마지막 페이지 체크 로직 보완 #85
pet-sitter/pets_next_door_flutter pull request #88
Opened 2024-02-11 14:44 UTC by juan-rybczinski

## Description
- Pagination API에 추가된 `is_last_page`을 적용했습니다.
- 개별 PaginationResponse가 기본 PaginationResponse를 extends 하도록 변경했습니다.

## Type of Change

- [ ] ✨ New feature (non-breaking change which adds functionality)
- [ ] 🛠️ Bug fix (non-breaking change which fixes an issue)
- [x] ❌ Breaking change (fix or feature that would cause existing functionality to change)
- [x] 🧹 Code refactor
- [ ] ✅ Build configuration change
- [ ] 📝 Documentation
- [ ] 🗑️ Chore

2024-02-11 14:47 UTC, juan-rybczinski commented on lib/features/pet/domain/breeds_pagination_response.dart
> +  ) : super.fromJson(json, (e) => Breed.fromJson(e));
개별 PaginationResponse들이 기본 PaginationResponse들을 기존에 `implements` 하던 것을 `extends` 하도록 변경해 불필요하게 반복되는 로직들을 제거했습니다.

2024-02-12 10:25 UTC, Yellowtoast requested changes

2024-02-12 10:25 UTC, Yellowtoast commented on lib/core/pagination/pagination_response.dart
> +      other is PaginationResponse &&
요 비교 로직에서 `other is PaginationResponse<T>` 로 비교하지 않아도 괜찮을까요?

2024-02-12 10:25 UTC, Yellowtoast commented on lib/features/pet/domain/breeds_pagination_response.dart
> +  ) : super.fromJson(json, (e) => Breed.fromJson(e));
PaginationResponse가 다른 클래스들의 순수한 is-a 관계인 것 같아 상속으로 바꿔도 좋을 것 같습니다!

2024-02-15 12:02 UTC, juan-rybczinski commented on lib/core/pagination/pagination_response.dart
> +      other is PaginationResponse &&
별 생각없이 IDE 자동 완성 기능으로 작성한 부분이었는데 Generic 타입이 달라도 같은 값이라고 판단하고 있었네요.

f827a27bb1c3bc461ebc7a9e07b78014f81fff64

2024-02-15 12:05 UTC, juan-rybczinski commented on lib/features/pet/domain/breeds_pagination_response.dart
> +  ) : super.fromJson(json, (e) => Breed.fromJson(e));
불필요하게 반복되는 코드를 줄여보자는 관점으로 접근 했었는데 `is-a`와 `has-a`로 `extends`와 `implements`를 판단할 수 있군요.

2024-02-20 05:08 UTC, Yellowtoast approved these changes
좋은 코드로 고쳐주셔서 감사합니다! 페이지네이션을 구현해주신 덕에 저도 돌봄급구 리스트를 금방 구현할 수 있었네요. 감사합니다! 👍

2024-02-20 10:50 UTC, merged